export const skuFields = [
    { label: "SKU Code*", key: "skuCode" },
    { label: "Category*", key: "category" },
    { label: "Sub Category", key: "subCategory" },
    { label: "Brand*", key: "brand" },
    { label: "Product Title*", key: "productTitle" },
    { label: "HSN*", key: "hsn" },
    { label: "EAN*", key: "ean" },
    { label: "Model Number*", key: "modelNumber" },
    { label: "Size", key: "size" },
    { label: "Color Family-Color", key: "colorFamilyColor" },
    { label: "Prdct L(cm)*", key: "productLengthCm" },
    { label: "Prdct B(cm)*", key: "productBreadthCm" },
    { label: "Prdct H(cm)*", key: "productHeightCm" },
    { label: "Wght(kg)*", key: "productWeightKg" },
    { label: "MSTRCTN Box Qty*", key: "masterCartonQty" },
    { label: "MSTRCTN L(cm)*", key: "masterCartonLengthCm" },
    { label: "MSTRCTN B(cm)*", key: "masterCartonBreadthCm" },
    { label: "MSTRCTN H(cm)*", key: "masterCartonHeightCm" },
    { label: "MSTRCTN Wght(kg)*", key: "masterCartonWeightKg" },
    { label: "MRP", key: "MRP" },
];
